export const metadata = {
  title: "myeonghwa's portfolio",
  description: "Generated by mh",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
