import '/public/reset.css';
import '@/styles/global.css';

export const metadata = {
  title: '손명화 포트폴리오',
  description: 'Generated by mh',
  icons: {
    icon: '/my_icon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
